services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "${DB_PORT}:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
